# Generated by Django 4.2.20 on 2025-03-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=20, unique=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('last_reading', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rental_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('electricity_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('electricity_bill', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('water_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('water_bill', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('security_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('previous_water_reading', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_water_reading', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.house')),
            ],
        ),
    ]
